import React, { useState, useRef, useEffect } from 'react';
import { Sparkles, Send, User, Bot, Trash2 } from 'lucide-react';
import { RhythmStyle, SeventhStringTuning, ChatMessage } from '../types';
import { sendCoachMessage } from '../services/geminiService';
import ReactMarkdown from 'react-markdown';

interface PracticeCoachProps {
  tuning: SeventhStringTuning;
  rhythm: RhythmStyle;
}

export const PracticeCoach: React.FC<PracticeCoachProps> = ({ tuning, rhythm }) => {
  const [messages, setMessages] = useState<ChatMessage[]>([
    { 
      role: 'model', 
      text: `Olá! Sou seu treinador de 7 cordas. Vejo que você está afinado em **${tuning.split('(')[0]}** e quer tocar **${rhythm}**. Como posso te ajudar hoje?` 
    }
  ]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  // Reset chat if context changes significantly? 
  // Maybe not, user might want to carry context, but let's notify the model via system instruction update in next call.
  // We can add a system message visually if the tuning changes, but let's keep it simple.

  const handleSend = async () => {
    if (!input.trim() || loading) return;

    const userMsg: ChatMessage = { role: 'user', text: input };
    setMessages(prev => [...prev, userMsg]);
    setInput("");
    setLoading(true);

    // Filter out the initial welcome message from history sent to API if it wasn't generated by the model dynamically,
    // but here we just send what we have. The API handles it.
    // Note: We exclude the very last user message from history param because we pass it as 'message' arg.
    const historyForApi = messages.slice(1); // Skip the hardcoded welcome message if you want, or keep it. 
    // Actually, sending the hardcoded welcome message as 'model' history is fine, it sets tone.

    const responseText = await sendCoachMessage(messages, input, tuning, rhythm);
    
    setMessages(prev => [...prev, { role: 'model', text: responseText }]);
    setLoading(false);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleQuickAction = () => {
    const actionText = `Crie um exercício de aquecimento para ${rhythm} usando a afinação ${tuning.split('(')[0]}.`;
    setInput(actionText);
    // Optional: auto send
    // handleSend(); -> can't easily call handleSend due to closure on input state, easier to just set input
  };

  const clearChat = () => {
    setMessages([{ 
      role: 'model', 
      text: `Olá! Vamos começar de novo. Afinador em **${tuning.split('(')[0]}**, ritmo **${rhythm}**. O que vamos praticar?` 
    }]);
  };

  return (
    <div className="bg-slate-800 rounded-2xl shadow-xl border border-slate-700 h-full flex flex-col overflow-hidden">
      {/* Header */}
      <div className="bg-slate-900/50 p-4 border-b border-slate-700 flex justify-between items-center">
        <div className="flex items-center gap-2 text-indigo-400">
          <Sparkles size={20} />
          <h2 className="font-bold">Treinador IA</h2>
        </div>
        <button 
          onClick={clearChat}
          className="text-slate-500 hover:text-red-400 transition-colors p-1"
          title="Limpar conversa"
        >
          <Trash2 size={16} />
        </button>
      </div>

      {/* Messages Area */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4 bg-slate-900/30">
        {messages.map((msg, idx) => {
          const isUser = msg.role === 'user';
          return (
            <div key={idx} className={`flex gap-3 ${isUser ? 'justify-end' : 'justify-start'}`}>
              {!isUser && (
                <div className="w-8 h-8 rounded-full bg-indigo-600 flex items-center justify-center flex-shrink-0 mt-1">
                  <Bot size={16} className="text-white" />
                </div>
              )}
              
              <div className={`
                max-w-[85%] rounded-2xl px-4 py-3 text-sm leading-relaxed
                ${isUser 
                  ? 'bg-indigo-600 text-white rounded-br-none' 
                  : 'bg-slate-700 text-slate-200 rounded-bl-none border border-slate-600'}
              `}>
                <ReactMarkdown 
                    components={{
                        // Tailor markdown styles
                        p: ({node, ...props}) => <p className="mb-2 last:mb-0" {...props} />,
                        ul: ({node, ...props}) => <ul className="list-disc ml-4 mb-2" {...props} />,
                        ol: ({node, ...props}) => <ol className="list-decimal ml-4 mb-2" {...props} />,
                        strong: ({node, ...props}) => <strong className="font-bold text-yellow-400" {...props} />,
                    }}
                >
                    {msg.text}
                </ReactMarkdown>
              </div>

              {isUser && (
                <div className="w-8 h-8 rounded-full bg-slate-600 flex items-center justify-center flex-shrink-0 mt-1">
                  <User size={16} className="text-slate-300" />
                </div>
              )}
            </div>
          );
        })}
        
        {loading && (
          <div className="flex gap-3 justify-start">
             <div className="w-8 h-8 rounded-full bg-indigo-600 flex items-center justify-center flex-shrink-0">
                <Bot size={16} className="text-white" />
             </div>
             <div className="bg-slate-700 rounded-2xl rounded-bl-none px-4 py-3 border border-slate-600 flex items-center gap-1">
                <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
             </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Input Area */}
      <div className="p-4 bg-slate-800 border-t border-slate-700">
        
        {messages.length < 3 && (
            <div className="mb-3 flex gap-2 overflow-x-auto pb-2 scrollbar-hide">
                <button 
                    onClick={handleQuickAction}
                    className="whitespace-nowrap px-3 py-1.5 bg-slate-700 hover:bg-slate-600 border border-slate-600 rounded-full text-xs text-indigo-300 transition-colors"
                >
                    ✨ Gerar exercício de aquecimento
                </button>
                <button 
                    onClick={() => setInput("Como usar a 7ª corda neste ritmo?")}
                    className="whitespace-nowrap px-3 py-1.5 bg-slate-700 hover:bg-slate-600 border border-slate-600 rounded-full text-xs text-slate-300 transition-colors"
                >
                    🎸 Como usar a 7ª corda?
                </button>
            </div>
        )}

        <div className="flex gap-2">
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Pergunte ao treinador..."
            className="flex-1 bg-slate-900 border border-slate-600 rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 resize-none h-[50px] scrollbar-hide"
            disabled={loading}
          />
          <button
            onClick={handleSend}
            disabled={!input.trim() || loading}
            className="bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-xl w-[50px] flex items-center justify-center transition-all shadow-lg shadow-indigo-900/20"
          >
            <Send size={20} />
          </button>
        </div>
      </div>
    </div>
  );
};